/* 咖啡沖煮模擬館：資料
 * 風味分數 0–10；quality 為豆子在理想沖煮下的杯測式潛力分數。
 * 冠軍配方整理自公開報導（Sprudge、European Coffee Trip、Barista Magazine、Slow Pour Supply、
 * World Coffee Championships 官網等），未公開的數值標為「推估」。
 */
(function (root) {
  'use strict';

  const BEANS = [
    { id: 'yirga', name: '衣索比亞 耶加雪菲', en: 'Ethiopia · Yirgacheffe', region: '南方州 蓋德奧區', alt: '1,900–2,200 m', variety: '原生種（JARC 74110、74112 等選育）', species: 'Arabica',
      p: { acid: 8.2, sweet: 6.8, body: 4.0, bitter: 2.0, aroma: 9.0, clarity: 8.6 }, quality: 88, common: ['washed', 'natural'],
      notes: [['茉莉花', 'floral'], ['佛手柑', 'citrus'], ['檸檬皮', 'citrus'], ['水蜜桃', 'stone'], ['紅茶', 'tea'], ['蜂蜜', 'sweet']],
      story: '咖啡的故鄉之一。高海拔、小農採收，水洗批次以茉莉與柑橘的清透感聞名，是淺焙手沖的教科書範本。' },
    { id: 'guji', name: '衣索比亞 古吉 罕貝拉', en: 'Ethiopia · Guji Hambela', region: '奧羅米亞州 古吉區', alt: '1,950–2,300 m', variety: '原生種', species: 'Arabica',
      p: { acid: 7.6, sweet: 7.6, body: 5.0, bitter: 2.0, aroma: 8.6, clarity: 7.8 }, quality: 88, common: ['natural', 'washed', 'anaerobic'],
      notes: [['水蜜桃', 'stone'], ['杏桃', 'stone'], ['柑橘', 'citrus'], ['白花', 'floral'], ['蔗糖', 'sweet']],
      story: '比耶加雪菲更甜、果汁感更濃，日曬批次常帶熟桃與莓果。' },
    { id: 'kenya', name: '肯亞 涅里 AA', en: 'Kenya · Nyeri AA', region: '中央省 涅里郡', alt: '1,700–1,900 m', variety: 'SL28、SL34、Ruiru 11、Batian', species: 'Arabica',
      p: { acid: 9.0, sweet: 6.6, body: 6.0, bitter: 2.5, aroma: 7.6, clarity: 8.2 }, quality: 88, common: ['washed'],
      notes: [['黑醋栗', 'berry'], ['葡萄柚', 'citrus'], ['番茄', 'savory'], ['紅葡萄', 'berry'], ['甘蔗', 'sweet']],
      story: '肯亞式水洗會發酵、清洗、再浸泡，酸質鮮明多汁，常被形容成黑醋栗和番茄。AA 指的是豆子尺寸等級，不是品質分數。' },
    { id: 'geisha', name: '巴拿馬 波奎特 藝伎', en: 'Panama · Boquete Geisha', region: '奇里基省 波奎特', alt: '1,600–1,900 m', variety: 'Geisha／Gesha', species: 'Arabica',
      p: { acid: 8.0, sweet: 8.2, body: 4.4, bitter: 1.6, aroma: 10, clarity: 9.4 }, quality: 92, common: ['washed', 'natural', 'anaerobic', 'carbonic'],
      notes: [['茉莉花', 'floral'], ['佛手柑', 'citrus'], ['柑橘花', 'floral'], ['芒果', 'tropical'], ['伯爵茶', 'tea'], ['蜂蜜', 'sweet']],
      story: '2004 年翡翠莊園在 Best of Panama 一戰成名。沖煮大賽決賽最常見的品種，花香與茶感極為立體。' },
    { id: 'huila', name: '哥倫比亞 薇拉', en: 'Colombia · Huila', region: '薇拉省', alt: '1,600–2,000 m', variety: 'Caturra、Castillo、Colombia', species: 'Arabica',
      p: { acid: 7.0, sweet: 7.6, body: 6.0, bitter: 2.6, aroma: 7.0, clarity: 7.6 }, quality: 85, common: ['washed', 'honey', 'anaerobic', 'thermal', 'yeast'],
      notes: [['紅蘋果', 'stone'], ['焦糖', 'sweet'], ['柳橙', 'citrus'], ['紅糖', 'sweet'], ['牛奶巧克力', 'choco']],
      story: '一年兩收、酸甜均衡的萬用產區。近年也是各種實驗性處理法的大本營。' },
    { id: 'antigua', name: '瓜地馬拉 安提瓜', en: 'Guatemala · Antigua', region: '薩卡特佩克斯省', alt: '1,500–1,700 m', variety: 'Bourbon、Caturra', species: 'Arabica',
      p: { acid: 6.4, sweet: 7.0, body: 7.0, bitter: 3.2, aroma: 7.0, clarity: 7.0 }, quality: 85, common: ['washed'],
      notes: [['可可', 'choco'], ['肉桂', 'spice'], ['太妃糖', 'sweet'], ['柳橙', 'citrus'], ['微煙燻', 'roast']],
      story: '火山灰土壤、三座火山環繞的谷地，典型風味是巧克力、香料與柔和的柑橘。' },
    { id: 'tarrazu', name: '哥斯大黎加 塔拉珠', en: 'Costa Rica · Tarrazú', region: '聖荷西省', alt: '1,500–1,900 m', variety: 'Caturra、Catuaí', species: 'Arabica',
      p: { acid: 7.0, sweet: 7.6, body: 6.0, bitter: 2.6, aroma: 7.2, clarity: 7.6 }, quality: 86, common: ['honey', 'washed', 'anaerobic'],
      notes: [['蜂蜜', 'sweet'], ['黑糖', 'sweet'], ['杏桃', 'stone'], ['柑橘', 'citrus'], ['可可', 'choco']],
      story: '「微處理廠革命」的發源地，蜜處理（白、黃、紅、黑蜜）在這裡被系統化。' },
    { id: 'cerrado', name: '巴西 喜拉朵', en: 'Brazil · Cerrado Mineiro', region: '米納斯吉拉斯州', alt: '900–1,250 m', variety: 'Mundo Novo、黃波旁、Catuaí', species: 'Arabica',
      p: { acid: 4.0, sweet: 7.0, body: 7.6, bitter: 3.6, aroma: 6.0, clarity: 6.2 }, quality: 83, common: ['natural', 'honey'],
      notes: [['花生', 'nut'], ['榛果', 'nut'], ['牛奶巧克力', 'choco'], ['焦糖', 'sweet'], ['黃糖', 'sweet']],
      story: '全世界最大產國的機械化產區。低酸、堅果巧克力調，是義式配方豆最常見的基底。' },
    { id: 'laurina', name: '巴西 尖身波旁（Laurina）', en: 'Brazil · Laurina', region: '米納斯吉拉斯州 喜拉朵', alt: '1,000–1,200 m', variety: 'Laurina（Bourbon Pointu，波旁的天然突變）', species: 'Arabica',
      p: { acid: 5.8, sweet: 8.0, body: 6.0, bitter: 1.6, aroma: 7.4, clarity: 7.8 }, quality: 88, common: ['natural', 'washed', 'honey'],
      notes: [['蜂蜜', 'sweet'], ['杏仁', 'nut'], ['紅茶', 'tea'], ['柑橘', 'citrus'], ['牛奶糖', 'sweet']],
      story: '天然低咖啡因（約阿拉比卡的一半）、豆形尖長的波旁突變種，產量低、栽種困難。2018 年深堀絵美用巴西 Daterra 莊園的 Laurina 奪下世界沖煮冠軍。' },
    { id: 'mandheling', name: '印尼 蘇門答臘 曼特寧', en: 'Indonesia · Sumatra Mandheling', region: '北蘇門答臘、亞齊', alt: '1,100–1,600 m', variety: 'Ateng、Tim Tim、Typica', species: 'Arabica',
      p: { acid: 3.4, sweet: 6.0, body: 9.0, bitter: 4.2, aroma: 6.6, clarity: 4.6 }, quality: 83, common: ['wethulled'],
      notes: [['雪松', 'wood'], ['草本', 'herbal'], ['黑巧克力', 'choco'], ['泥土', 'earthy'], ['香料', 'spice']],
      story: '潮濕氣候造就了「濕剝法」，帶來厚實、低酸、帶木質與草本的經典風味，在臺灣尤其受歡迎。' },
    { id: 'yemen', name: '葉門 哈拉茲', en: 'Yemen · Haraaz', region: '薩那省 哈拉茲山區', alt: '1,800–2,400 m', variety: 'Yemenia、Udaini', species: 'Arabica',
      p: { acid: 6.4, sweet: 7.2, body: 7.0, bitter: 2.8, aroma: 8.4, clarity: 6.0 }, quality: 87, common: ['natural'],
      notes: [['葡萄乾', 'berry'], ['紅酒', 'ferment'], ['小豆蔻', 'spice'], ['可可', 'choco'], ['無花果', 'stone']],
      story: '「摩卡」一詞來自葉門的摩卡港。梯田、乾燥氣候、傳統日曬，風味帶乾果與香料。' },
    { id: 'rwanda', name: '盧安達 尼亞馬舍克', en: 'Rwanda · Nyamasheke', region: '西方省 基伍湖畔', alt: '1,700–2,000 m', variety: '紅波旁', species: 'Arabica',
      p: { acid: 7.6, sweet: 7.0, body: 5.4, bitter: 2.4, aroma: 7.6, clarity: 8.0 }, quality: 86, common: ['washed', 'natural'],
      notes: [['紅莓', 'berry'], ['紅茶', 'tea'], ['柳橙', 'citrus'], ['焦糖', 'sweet'], ['玫瑰', 'floral']],
      story: '基伍湖畔的水洗處理站提供清甜的紅波旁。偶有「馬鈴薯味」瑕疵（由蟲害相關的細菌引起），是東非特有的問題。' },
    { id: 'alishan', name: '臺灣 嘉義 阿里山', en: 'Taiwan · Alishan', region: '嘉義縣 阿里山鄉', alt: '1,000–1,400 m', variety: 'Typica、Geisha、SL34', species: 'Arabica',
      p: { acid: 6.6, sweet: 7.6, body: 5.4, bitter: 2.2, aroma: 7.6, clarity: 8.2 }, quality: 86, common: ['washed', 'honey', 'natural', 'anaerobic'],
      notes: [['烏龍茶', 'tea'], ['蜂蜜', 'sweet'], ['柑橘', 'citrus'], ['甘蔗', 'sweet'], ['桂花', 'floral']],
      story: '產量少、人工成本高，但茶園轉作的精緻管理讓阿里山咖啡在國際競標屢創高價，風味常帶烏龍茶般的回甘。' },
    { id: 'bluemountain', name: '牙買加 藍山', en: 'Jamaica · Blue Mountain', region: '藍山山脈', alt: '900–1,700 m', variety: 'Typica', species: 'Arabica',
      p: { acid: 5.6, sweet: 7.0, body: 6.0, bitter: 2.6, aroma: 7.0, clarity: 7.6 }, quality: 84, common: ['washed'],
      notes: [['堅果', 'nut'], ['牛奶巧克力', 'choco'], ['柔和柑橘', 'citrus'], ['奶油', 'sweet']],
      story: '受法律保護的產區名稱，以「均衡、溫和、不刺激」著稱，是許多人的第一支精品咖啡。' },
    { id: 'robusta', name: '越南 中央高地 羅布斯塔', en: 'Vietnam · Robusta', region: '得樂省', alt: '500–800 m', variety: 'Coffea canephora', species: 'Robusta',
      p: { acid: 2.4, sweet: 4.0, body: 9.0, bitter: 7.4, aroma: 5.0, clarity: 4.0 }, quality: 78, common: ['natural', 'washed'], sol: 1.05,
      notes: [['黑巧克力', 'choco'], ['烤穀物', 'roast'], ['木質', 'wood'], ['黑糖', 'sweet']],
      story: '咖啡因約為阿拉比卡的兩倍（約 2.2–2.7% 對 1.2–1.5%），綠原酸多、糖少，苦味重、油脂多，是越南滴滴壺與義式配方增加 crema 的常客。' }
  ];

  const PROCESSES = [
    { id: 'washed', name: '水洗', en: 'Washed', d: { acid: 0.8, sweet: 0, body: -0.5, clarity: 1.2, ferment: 0 }, notes: [],
      steps: ['採收成熟紅果', '脫皮機去除果皮果肉', '發酵槽 12–72 小時分解果膠', '清水洗淨', '棚架日曬或機械乾燥至含水率 10–12%', '去除羊皮層成為生豆'],
      summary: '把果肉與果膠洗掉再乾燥。風味主要來自品種與產地，所以乾淨、酸質明亮、辨識度高。', time: '約 2–3 週', risk: '用水量大；發酵過度會產生醋酸味。' },
    { id: 'natural', name: '日曬', en: 'Natural / Dry', d: { acid: -0.3, sweet: 1.3, body: 1.2, clarity: -1.0, ferment: 1.5 }, notes: [['藍莓', 'berry'], ['草莓', 'berry'], ['熱帶水果', 'tropical'], ['酒香', 'ferment']],
      steps: ['採收整顆果實', '浮選去除瑕疵果', '整顆攤在高架棚上日曬', '每天翻動 3–4 次防止發霉', '2–4 週乾燥至含水率 11%', '脫去乾果殼'],
      summary: '果肉包著種子一起曬乾，糖分與發酵產物讓風味更甜、更有果醬與酒香，醇厚度高，但乾淨度較低。', time: '約 2–4 週', risk: '翻動不均會發霉或過度發酵；批次一致性較難控制。' },
    { id: 'honey', name: '蜜處理', en: 'Honey / Pulped Natural', d: { acid: 0, sweet: 1.0, body: 0.6, clarity: 0.1, ferment: 0.5 }, notes: [['黑糖', 'sweet'], ['杏桃', 'stone'], ['楓糖', 'sweet']],
      steps: ['採收紅果', '去除果皮，保留果膠（黏質）', '依保留比例分白、黃、紅、黑蜜', '棚架乾燥，需頻繁翻動', '1–3 週乾燥', '去殼'],
      summary: '介於水洗與日曬之間。保留越多果膠、乾得越慢（黑蜜），甜感與醇厚越高；白蜜則接近水洗的乾淨。', time: '約 1–3 週', risk: '果膠黏膩，容易結塊發霉。' },
    { id: 'anaerobic', name: '厭氧發酵', en: 'Anaerobic Fermentation', d: { acid: 0.3, sweet: 0.8, body: 0.8, clarity: -0.5, ferment: 3.0 }, notes: [['肉桂', 'spice'], ['酒釀', 'ferment'], ['優格', 'ferment'], ['熱帶水果', 'tropical']],
      steps: ['採收紅果（可去皮或不去皮）', '放入密封槽並排出氧氣', '控制溫度發酵 48–120 小時，監測 pH 與糖度', '依設計選擇水洗或日曬收尾', '乾燥至含水率 11%'],
      summary: '在無氧環境中讓乳酸菌與酵母主導發酵，產生強烈的香料、酒釀與熱帶水果風味，辨識度極高。', time: '約 3–5 週', risk: '風味可能蓋過產地特色；過頭會出現醬油、藥水味。' },
    { id: 'carbonic', name: '二氧化碳浸漬', en: 'Carbonic Maceration', d: { acid: 0.5, sweet: 1.0, body: 0.6, clarity: 0.2, ferment: 2.2 }, notes: [['紅酒', 'ferment'], ['葡萄', 'berry'], ['肉桂', 'spice'], ['櫻桃', 'berry']],
      steps: ['整顆果實放入不鏽鋼槽', '灌入 CO₂ 置換氧氣', '果實細胞內發酵數十到上百小時', '取出日曬或乾燥'],
      summary: '借自薄酒萊葡萄酒的釀造法。2015 年 Sasa Sestic 以此奪得世界咖啡師冠軍，2022 年徐詩媛的冠軍豆也是 CO₂ 浸漬日曬藝伎。', time: '約 3–5 週', risk: '設備與監控成本高。' },
    { id: 'wethulled', name: '濕剝法', en: 'Wet-hulled (Giling Basah)', d: { acid: -1.5, sweet: 0, body: 2.0, clarity: -1.5, ferment: 0.3 }, notes: [['雪松', 'wood'], ['草本', 'herbal'], ['泥土', 'earthy'], ['菸草', 'wood']],
      steps: ['小農去皮、短時間發酵', '含水率 30–50% 時就剝除羊皮層', '裸露的生豆直接曬乾', '運到港口再乾燥至 12%'],
      summary: '為了潮濕氣候與快速現金流而生的印尼特有做法。豆子呈藍綠色，風味厚重、低酸，帶木質與草本。', time: '約 1–2 週', risk: '生豆容易受損、瑕疵率高。' },
    { id: 'yeast', name: '酵母接種', en: 'Yeast Inoculation', d: { acid: 0.3, sweet: 0.8, body: 0.2, clarity: 0.5, ferment: 1.2 }, notes: [['白葡萄', 'berry'], ['花香', 'floral'], ['熟成水果', 'stone']],
      steps: ['去皮後的咖啡放入發酵槽', '加入選定的酵母菌株（葡萄酒、啤酒或咖啡專用）', '控制溫度與時間', '水洗或日曬收尾'],
      summary: '用特定菌株取代野生微生物，讓發酵結果更可預測，提升甜感與乾淨的果香。', time: '約 2–4 週', risk: '菌株選擇會強烈改變風味方向。' },
    { id: 'thermal', name: '熱衝擊', en: 'Thermal Shock', d: { acid: 0.6, sweet: 1.2, body: 0.3, clarity: 0.8, ferment: 2.0 }, notes: [['荔枝', 'tropical'], ['百香果', 'tropical'], ['玫瑰', 'floral'], ['草莓糖', 'berry']],
      steps: ['兩階段厭氧發酵', '以約 40°C 熱水沖洗，讓風味物質進入種子', '再以約 12°C 冷水沖洗「鎖住」風味', '控溫乾燥'],
      summary: '哥倫比亞 Finca El Paraíso 的 Diego Bermúdez 推廣的做法，風味鮮豔、甜度極高，在比賽中很常見。', time: '約 3–4 週', risk: '爭議在於風味是否仍代表產地。' }
  ];

  const ROAST_INFO = [
    { id: 'xlight', name: '極淺焙', en: 'Nordic', tile: 95, color: '#b98555', drop: '一爆中段出爐', d: { acid: 1.6, sweet: -0.6, body: -1.1, bitter: -1.2, aroma: 0.4 }, temp: [94, 97], notes: [['青蘋果', 'citrus'], ['花香', 'floral']], desc: '酸質最強、茶感明顯；沖煮需要高溫與較細研磨，否則容易萃取不足。' },
    { id: 'light', name: '淺焙', en: 'Light', tile: 85, color: '#a26a3c', drop: '一爆結束', d: { acid: 1.0, sweet: 0, body: -0.5, bitter: -0.6, aroma: 0.5 }, temp: [93, 96], notes: [], desc: '保留產地與處理法特色，花果香最清楚。精品手沖與沖煮大賽的主流。' },
    { id: 'mlight', name: '中淺焙', en: 'City', tile: 75, color: '#8a5530', drop: '一爆後 1–2 分鐘', d: { acid: 0.5, sweet: 0.4, body: 0, bitter: 0, aroma: 0.3 }, temp: [92, 95], notes: [['焦糖', 'sweet']], desc: '酸甜平衡，最能兼顧果香與焦糖甜感，也適合淺焙義式。' },
    { id: 'medium', name: '中焙', en: 'City+', tile: 65, color: '#6f4226', drop: '二爆前', d: { acid: 0, sweet: 0.6, body: 0.5, bitter: 0.8, aroma: 0 }, temp: [90, 94], notes: [['焦糖', 'sweet'], ['牛奶巧克力', 'choco']], desc: '甜感與醇厚度高峰，堅果、焦糖、巧克力浮現。' },
    { id: 'mdark', name: '中深焙', en: 'Full City', tile: 55, color: '#56321d', drop: '二爆初', d: { acid: -1.0, sweet: 0.3, body: 1.0, bitter: 2.0, aroma: -0.3 }, temp: [88, 92], notes: [['黑巧克力', 'choco'], ['烤堅果', 'nut']], desc: '開始出現烘焙味，酸質退場。傳統義式與拿鐵的常用焙度。' },
    { id: 'dark', name: '深焙', en: 'Vienna / French', tile: 45, color: '#3d2415', drop: '二爆中', d: { acid: -2.0, sweet: -0.5, body: 1.2, bitter: 3.5, aroma: -0.8 }, temp: [85, 90], notes: [['煙燻', 'roast'], ['黑巧克力', 'choco'], ['焦糖化糖', 'sweet']], desc: '表面出油，苦味與煙燻主導。適合低溫、較粗研磨，或加牛奶。' },
    { id: 'xdark', name: '極深焙', en: 'Italian', tile: 35, color: '#2a1810', drop: '二爆結束', d: { acid: -3.0, sweet: -1.5, body: 1.0, bitter: 4.5, aroma: -1.5 }, temp: [83, 88], notes: [['炭燒', 'roast'], ['焦苦', 'roast']], desc: '產地特色幾乎被烘焙味取代，苦、焦、油脂多。' }
  ];

  const GRINDER_INFO = [
    { id: 'premium', name: '大刀盤平刀', desc: '例如 98 mm 以上平刀，顆粒最均勻、細粉最少' },
    { id: 'flat', name: '平刀磨豆機', desc: '顆粒均勻，乾淨度高' },
    { id: 'conical', name: '錐刀磨豆機', desc: '手搖磨豆機與多數家用機，細粉稍多、醇厚' },
    { id: 'blade', name: '刀片式', desc: '其實是「打碎」，粗細差異極大' }
  ];

  const WATER_INFO = [
    { id: 'ro', name: '純水／RO 水', spec: 'TDS 約 0 ppm', desc: '沒有礦物質幫忙抓取風味，喝起來扁平、空洞。' },
    { id: 'soft', name: '軟水', spec: 'TDS 約 50 ppm', desc: '酸質明亮、乾淨，但醇厚稍弱。' },
    { id: 'sca', name: 'SCA 標準水', spec: 'TDS 150 ppm · 鈣硬度 68 · 鹼度 40', desc: '精品咖啡協會建議的平衡水質。' },
    { id: 'mg', name: '高鎂低鹼調配水', spec: '硬度約 70（以鎂為主）· 鹼度約 20', desc: '鎂離子較容易與果酸、芳香物結合，比賽常用。' },
    { id: 'hard', name: '高硬度高鹼度水', spec: 'TDS 300+ · 鹼度 150', desc: '碳酸氫根中和酸質，喝起來悶、鈍；也容易讓機器結垢。' }
  ];

  const P = (rows) => rows.map(([t, g, o]) => Object.assign({ t, g }, o || {}));

  /* 沖煮方法 */
  const METHODS = [
    { id: 'v60', name: 'Hario V60', cat: 'pour', family: 'perc', draw: 'cone', filter: 'paper', phys: { tau0: 16, bypass: 0.08 },
      target: 'filter', grindRange: [500, 800],
      def: { dose: 15, water: 250, temp: 93, grind: 600, schedule: P([[0, 40, { style: 'spiral' }], [45, 110], [90, 100]]) },
      info: { origin: '日本 Hario，2004 年', principle: '60° 錐形、單一大孔、內壁螺旋肋。流速幾乎全靠研磨與注水控制，自由度最高。', flavor: '明亮、乾淨、層次清楚。', ratio: '1:15–1:17', time: '2:30–3:30',
        tips: ['悶蒸用粉量 2–3 倍的水，等 30–45 秒讓 CO₂ 排出', '注水高度與速度保持一致', '最後輕搖濾杯讓粉床平整'], mistakes: ['沿著濾紙注水造成旁流（bypass）', '細粉過多導致下水塞住、苦澀'] } },
    { id: 'origami', name: 'Origami 摺紙濾杯', cat: 'pour', family: 'perc', draw: 'origami', filter: 'paper', phys: { tau0: 14, bypass: 0.07 },
      target: 'filter', grindRange: [550, 850],
      def: { dose: 15, water: 240, temp: 93, grind: 600, schedule: P([[0, 40], [40, 100], [80, 100]]) },
      info: { origin: '日本美濃燒瓷器', principle: '20 道摺痕讓濾紙與杯壁間留出空氣通道，流速快。可以用錐形或蛋糕濾紙，一杯兩用。', flavor: '用錐形濾紙時明亮輕盈；用蛋糕濾紙時甜感圓潤。', ratio: '1:15–1:16', time: '2:00–3:00',
        tips: ['流速快，研磨可以稍細', '2019 杜佳寧、2023 Carlos Medina 都用它奪冠'], mistakes: ['注水太快讓粉層被沖成坑洞'] } },
    { id: 'kalita', name: 'Kalita Wave 蛋糕濾杯', cat: 'pour', family: 'perc', draw: 'flat', filter: 'paper', phys: { tau0: 26, bypass: 0.03 },
      target: 'filter', grindRange: [550, 850],
      def: { dose: 20, water: 320, temp: 93, grind: 700, schedule: P([[0, 50], [40, 90], [80, 90], [120, 90]]) },
      info: { origin: '日本 Kalita', principle: '平底、三個小孔、波浪濾紙減少與杯壁接觸。粉床平整，萃取均勻，容錯率高。', flavor: '甜感足、圓潤、穩定。', ratio: '1:15–1:16', time: '3:00–3:45',
        tips: ['適合脈衝式小量多次注水', '平底讓每顆粉接觸時間接近'], mistakes: ['水位太高時水會從側邊流走'] } },
    { id: 'chemex', name: 'Chemex', cat: 'pour', family: 'perc', draw: 'chemex', filter: 'thickpaper', phys: { tau0: 34, bypass: 0.02, absorb: 2.2 },
      target: 'filter', grindRange: [700, 1000],
      def: { dose: 30, water: 500, temp: 94, grind: 800, schedule: P([[0, 70], [45, 150], [90, 150], [135, 130]]) },
      info: { origin: '1941 年德國化學家 Peter Schlumbohm 發明', principle: '一體成形的玻璃燒瓶，加上比一般厚 20–30% 的濾紙，攔下更多油脂與細粉。', flavor: '極度乾淨、清爽、茶感。', ratio: '1:15–1:17', time: '4:00–5:00',
        tips: ['厚濾紙下水慢，研磨要粗', '濾紙三層那側對著出水口，避免貼住氣道'], mistakes: ['研磨太細導致超過 6 分鐘'] } },
    { id: 'orea', name: 'OREA 平底快速濾杯', cat: 'pour', family: 'perc', draw: 'flat', filter: 'paper', phys: { tau0: 12, bypass: 0.05 },
      target: 'filter', grindRange: [550, 800],
      def: { dose: 17, water: 270, temp: 93, grind: 630, schedule: P([[0, 60], [30, 60], [45, 50, { dur: 35 }], [80, 100, { dur: 40 }]]) },
      info: { origin: '英國 OREA，2024 冠軍 Martin Wölfl 使用 V4 Fast', principle: '平底加上大開孔底座，流速非常快；可以用更細的研磨換取萃取，同時保持短時間。', flavor: '清晰、多汁、甜感集中。', ratio: '1:15–1:16', time: '2:00–2:30',
        tips: ['快速濾杯的邏輯是「細研磨＋短時間」', '搭配快速濾紙（如 Sibarist FAST）'], mistakes: ['研磨太粗會淡而無味'] } },
    { id: 'clever', name: '聰明濾杯', cat: 'hybrid', family: 'valve', draw: 'clever', filter: 'paper', phys: { tau0: 22, bypass: 0 },
      target: 'filter', grindRange: [600, 900],
      def: { dose: 20, water: 300, temp: 94, grind: 700, steep: 180, stirs: [30] },
      info: { origin: '臺灣發明（ABID 聰明濾杯）', principle: '底部有止水閥：放在桌上時關閉、浸泡；放上杯子就打開、過濾。浸泡的穩定加上濾紙的乾淨。', flavor: '甜、厚、乾淨，容錯率高。', ratio: '1:14–1:16', time: '3:00–4:00',
        tips: ['先放水再放粉可以減少塞住', '浸泡時間比研磨更好調'], mistakes: ['研磨太細，打開閥門後過濾太久'] } },
    { id: 'switch', name: '閥門式混合濾杯', cat: 'hybrid', family: 'valve', draw: 'clever', filter: 'paper', phys: { tau0: 18, bypass: 0.04 },
      target: 'filter', grindRange: [550, 850],
      def: { dose: 16, water: 250, temp: 94, grind: 650, schedule: P([[0, 50, { valve: 'close' }], [40, 200, { dur: 30, valve: 'close' }]]), events: [{ t: 120, type: 'valve', open: true }] },
      info: { origin: 'Hario Switch、GINA 等', principle: '錐形濾杯加上可隨時開關的閥門，可以在一杯裡自由切換浸泡與滴濾。2018 深堀絵美就是用 GINA 的閥門設計，交替浸泡與滴濾奪冠。', flavor: '可以同時拿到浸泡的甜與滴濾的清晰。', ratio: '1:13–1:16', time: '2:30–3:30',
        tips: ['在每一段注水設定閥門開或關', '低溫浸泡、高溫滴濾是常見組合'], mistakes: ['關閥太久加上高溫會過萃'] } },
    { id: 'frenchpress', name: '法式濾壓壺', cat: 'immersion', family: 'immersion', draw: 'press', filter: 'metal', phys: { releaseTau: 6, heatTau: 3000 },
      target: 'filter', grindRange: [850, 1300],
      def: { dose: 30, water: 500, temp: 96, grind: 900, steep: 240, stirs: [30], mode: 'plunge' },
      info: { origin: '1929 年義大利人 Attilio Calimani 取得專利', principle: '全浸泡後以金屬濾網下壓分離。金屬網讓油脂與細粉通過，口感最厚實。', flavor: '醇厚、油脂感、圓潤，但較混濁。', ratio: '1:12–1:16', time: '4:00（Hoffmann 法 9 分鐘以上）',
        tips: ['下壓只是「分離」，不要用力壓', 'Hoffmann 法：4 分鐘破渣撇沫，再靜置 5–8 分鐘讓細粉沉澱'], mistakes: ['研磨太細造成混濁、苦澀', '壓完放著沒倒出，繼續萃取'] } },
    { id: 'aeropress', name: '愛樂壓 AeroPress', cat: 'immersion', family: 'immersion', draw: 'aero', filter: 'paper', phys: { releaseTau: 9, heatTau: 1400, absorb: 1.1 },
      target: 'filter', grindRange: [450, 900],
      def: { dose: 15, water: 230, temp: 95, grind: 560, steep: 105, stirs: [15], press: 30, dilute: 0 },
      info: { origin: '2005 年 Alan Adler 發明；2008 年起舉辦世界愛樂壓大賽（WAC）', principle: '浸泡後用手動活塞加壓，把液體推過濾紙。可正放、可倒置，參數自由度極高。', flavor: '乾淨又有厚度，可做成濃縮後加水。', ratio: '1:10–1:17', time: '1:30–2:30',
        tips: ['倒置法可以避免浸泡時滴漏', '壓到聽見「嘶」聲就停，避免擠出苦味'], mistakes: ['用力快壓讓細粉通過濾紙'] } },
    { id: 'siphon', name: '虹吸壺', cat: 'immersion', family: 'immersion', draw: 'siphon', filter: 'cloth', phys: { releaseTau: 14, hold: 92, heatTau: 1e9 },
      target: 'filter', grindRange: [500, 800],
      def: { dose: 20, water: 300, temp: 92, grind: 560, steep: 75, stirs: [5, 70] },
      info: { origin: '1830 年代德國與法國', principle: '下壺加熱產生蒸氣壓，把熱水推到上壺與粉浸泡；關火後下壺冷卻形成負壓，把咖啡吸下來經過濾布。全程有熱源，溫度穩定。', flavor: '香氣高、口感圓滑、乾淨度介於濾紙與金屬網之間。', ratio: '1:14–1:16', time: '1:00–1:30 浸泡',
        tips: ['布濾器要泡在水裡保存', '攪拌次數與力道決定萃取量'], mistakes: ['火太大導致上壺沸騰過萃'] } },
    { id: 'coldbrew', name: '冷萃', cat: 'immersion', family: 'immersion', draw: 'jar', filter: 'paper', phys: { releaseTau: 200, dt: 20 },
      target: 'cold', grindRange: [900, 1500],
      def: { dose: 100, water: 1000, temp: 20, grind: 1100, hours: 16, fridge: false, stirs: [60] },
      info: { origin: '日本「水出し」與美國冷萃文化', principle: '用冷水長時間浸泡。低溫下苦味與部分酸類溶解度低，得到低苦、低酸、甜順的咖啡。', flavor: '巧克力、焦糖、低酸、滑順。', ratio: '1:8（濃縮液）–1:15（直接喝）', time: '12–20 小時',
        tips: ['冰箱冷藏萃取更慢，時間要拉長', '濃縮液可加水或牛奶稀釋'], mistakes: ['室溫浸泡超過 24 小時可能出現木質、氧化味'] } },
    { id: 'espresso', name: '義式濃縮', cat: 'pressure', family: 'espresso', draw: 'espresso', filter: 'metal',
      target: 'espresso', grindRange: [180, 450],
      def: { dose: 18, yield: 36, temp: 93, grind: 240, pressure: 9, preinf: 0, prep: 'wdt' },
      info: { origin: '1901 年 Luigi Bezzera 取得專利；1947 年 Gaggia 的拉桿機帶來 9 bar 與 crema', principle: '約 9 bar 壓力把熱水推過緊壓的細粉餅，25–35 秒得到濃度約 8–12% 的濃縮液。流速由研磨細度與粉餅阻力決定。', flavor: '濃郁、甜、酸苦並陳，表面有 crema。', ratio: '1:1.5–1:3', time: '25–35 秒',
        tips: ['先用粉量與出杯量定比例，再用研磨調時間', 'WDT 布粉能大幅減少通道效應'], mistakes: ['研磨太細造成通道效應：同時又酸又苦', '只看時間不看出杯重'] } },
    { id: 'moka', name: '摩卡壺', cat: 'pressure', family: 'moka', draw: 'moka', filter: 'metal',
      target: 'moka', grindRange: [300, 550],
      def: { dose: 15, water: 150, temp: 95, grind: 380, heat: 'med', hotStart: true },
      info: { origin: '1933 年 Alfonso Bialetti', principle: '下壺水加熱後蒸氣壓（約 1–1.5 bar）把熱水推過粉槽，進入上壺。壓力遠低於義式，是「有壓力的滴濾」。', flavor: '濃、厚、帶烘焙香，濃度介於滴濾與義式之間。', ratio: '1:7–1:10', time: '出液約 1–2 分鐘',
        tips: ['下壺直接倒熱水，縮短粉在壺裡被烤的時間', '聽到咕嚕聲就離火，並用冷水冷卻壺底'], mistakes: ['火太大，最後的蒸氣噴發帶來焦苦', '把粉壓實（摩卡壺不需要填壓）'] } },
    { id: 'turkish', name: '土耳其咖啡', cat: 'traditional', family: 'turkish', draw: 'cezve', filter: 'none',
      target: 'turkish', grindRange: [80, 200],
      def: { dose: 7, water: 70, temp: 100, grind: 120, boils: 1, heat: 'med', sugar: 'none' },
      info: { origin: '16 世紀鄂圖曼帝國；2013 年列入聯合國教科文組織非物質文化遺產', principle: '極細如麵粉的咖啡粉與冷水（可加糖）一起放入銅壺 cezve，小火加熱至泡沫升起即離火，不過濾、連粉帶液倒入杯中。', flavor: '極濃、厚重、有沙沙的口感與泡沫。', ratio: '1:9–1:12', time: '3–4 分鐘',
        tips: ['泡沫是品質的指標，小火慢煮', '倒入後靜置一分鐘讓粉沉底'], mistakes: ['煮到沸騰翻滾，泡沫消失、焦苦'] } },
    { id: 'phin', name: '越南滴滴壺', cat: 'traditional', family: 'perc', draw: 'phin', filter: 'metal', kAdj: 1.35, phys: { tau0: 22, bypass: 0, heatTau: 500, absorb: 1.8, layers: [0.5, 0.5] },
      target: 'phin', grindRange: [350, 650],
      def: { dose: 20, water: 100, temp: 96, grind: 420, tamp: 'light', milk: true, schedule: P([[0, 20], [40, 80, { dur: 15, style: 'center' }]]) },
      info: { origin: '19 世紀法國殖民時期傳入越南', principle: '金屬小濾杯加上壓板，靠重力慢慢滴 4–5 分鐘。傳統上搭配深焙羅布斯塔與煉乳（cà phê sữa đá）。', flavor: '極濃、苦甜、厚重。', ratio: '1:4–1:6', time: '4–5 分鐘',
        tips: ['壓板輕放或輕旋，壓太緊會滴不下來', '先加 20 g 水悶蒸 30 秒'], mistakes: ['研磨太細塞住，滴超過 8 分鐘'] } },
    { id: 'colddrip', name: '冰滴（京都式）', cat: 'traditional', family: 'perc', draw: 'tower', filter: 'paper', phys: { tau0: 40, bypass: 0, dt: 2 },
      target: 'cold', grindRange: [450, 800],
      def: { dose: 50, water: 500, temp: 8, grind: 600, dripRate: 1.0 },
      info: { origin: '據傳源自荷蘭商人在亞洲的航海需求，後在日本京都發揚', principle: '冰水一滴一滴通過粉層，數小時完成。和冷萃同樣是低溫，但屬於滲濾，口感更乾淨，常帶酒香。', flavor: '清爽、甜、低苦，冷藏熟成後帶酒香。', ratio: '1:8–1:12', time: '3–8 小時',
        tips: ['每秒約 1 滴是常見設定', '先用少量水把粉層均勻打濕'], mistakes: ['滴速太快造成通道，淡而無味'] } }
  ];

  /* 各方法的理想區間（EY %、TDS %） */
  const TARGETS = {
    filter:   { ey: [18, 22], tds: [1.15, 1.45], tdsAxis: [0.6, 2.2], label: '滴濾／浸泡（SCA 金杯）' },
    espresso: { ey: [18, 22], tds: [7.5, 12], tdsAxis: [4, 16], label: '義式濃縮' },
    moka:     { ey: [18, 22], tds: [2.2, 4.0], tdsAxis: [1, 6], label: '摩卡壺' },
    turkish:  { ey: [20, 26], tds: [2.0, 3.5], tdsAxis: [1, 5], label: '土耳其咖啡' },
    phin:     { ey: [16, 22], tds: [3.5, 7.0], tdsAxis: [1.5, 9], label: '越南滴滴壺' },
    cold:     { ey: [15, 20], tds: [1.4, 2.4], tdsAxis: [0.6, 3.4], label: '冷萃／冰滴（濃縮液）' }
  };

  const STYLE_NAMES = { spiral: '繞圈', center: '中心定點', pulse: '脈衝', stir: '攪拌', melodrip: '分水網' };

  /* 冠軍與名人配方 */
  const RECIPES = [
    { id: 'tetsu46', year: 2016, comp: 'WBrC', who: '粕谷哲', en: 'Tetsu Kasuya', country: '日本', title: '4:6 法',
      bean: 'yirga', process: 'washed', roast: 'light', method: 'v60',
      cfg: { dose: 20, water: 300, temp: 92, grind: 800, schedule: P([[0, 50], [45, 70], [90, 60], [130, 60], [165, 60]]) },
      steps: ['20 g 粗研磨，300 g 水（1:15），92°C', '前 40%（120 g）分兩段：50 g → 70 g，控制酸甜', '後 60%（180 g）分三段各 60 g，控制濃度', '每段約 45 秒，3:30 移開濾杯'],
      idea: '把水量拆成兩個功能：前 40% 決定酸甜平衡（第一注少會比較甜、多會比較酸），後 60% 決定濃淡（分越多段越濃）。規則簡單到能教給所有人，這是他奪冠的關鍵。',
      src: '公開發表的 4:6 法；溫度依烘焙度可調' },
    { id: 'chad2017', year: 2017, comp: 'WBrC', who: '王策', en: 'Chad Wang', country: '臺灣', title: '中心定點注水',
      bean: 'geisha', process: 'washed', roast: 'light', method: 'v60',
      cfg: { dose: 15, water: 250, temp: 92, grind: 520, schedule: P([[0, 30, { style: 'spiral' }], [30, 220, { style: 'center', dur: 45 }]]) },
      steps: ['15 g 中細研磨（Ditting KR804 刻度 4.5–5.5）', '92°C，30 g 悶蒸 30 秒', '剩下的水全部對準中心注入，不繞圈', '總時間約 2:00，約 220 ml 飲品'],
      idea: '只悶蒸一次，之後對中心穩定注水、不繞圈，讓粉層保持完整、減少擾動。他的經驗法則是：烘焙越深，粉水比越小、研磨越粗。濾杯型號未公開，模擬以 V60 近似。',
      src: 'Barista Magazine、Long & Short London' },
    { id: 'emi2018', year: 2018, comp: 'WBrC', who: '深堀絵美', en: 'Emi Fukahori', country: '瑞士', title: '浸泡＋滴濾混合',
      bean: 'laurina', process: 'natural', roast: 'light', method: 'switch',
      cfg: { dose: 17, water: 220, temp: 95, grind: 580, schedule: P([[0, 50, { temp: 80, valve: 'close' }], [45, 100, { temp: 95, valve: 'open', dur: 20 }], [105, 70, { temp: 80, valve: 'close' }]]), events: [{ t: 130, type: 'valve', open: true }] },
      steps: ['17 g 粉、220 g 水，GINA 閥門式濾杯', '第一段 50 g、80°C，關閥浸泡 45 秒', '第二段 100 g、95°C，開閥滴濾約 1 分鐘', '第三段 70 g、80°C，關閥浸泡 25 秒後開閥', '總時間約 2:55'],
      idea: '史上第一位女性世界沖煮冠軍。用低溫浸泡帶出甜感，高溫滴濾「打開」風味，再低溫收尾得到乾淨的尾韻。使用巴西 Daterra 莊園的 Laurina 品種（批次名 Frevo），處理法在模擬中以日曬近似。',
      src: 'European Coffee Trip、BeanScene、GOAT STORY' },
    { id: 'du2019', year: 2019, comp: 'WBrC', who: '杜佳寧', en: 'Du Jianing', country: '中國', title: '二次研磨＋自調水',
      bean: 'geisha', process: 'natural', roast: 'light', method: 'origami',
      cfg: { dose: 16, water: 240, temp: 94, grind: 580, grinder: 'flat', waterProfile: 'mg', schedule: P([[0, 60], [18, 80, { dur: 14 }], [56, 100, { dur: 18 }]]) },
      steps: ['16 g 粉、240 g 水、94°C，Origami 濾杯', '先粗磨去除銀皮，再磨到中等細度', '0:00 注 60 g → 0:18 注 80 g → 0:56 注到 240 g', '總時間約 1:46', '自調水：加入少量鈣、鎂，總 TDS 約 80 ppm'],
      idea: '中國第一位世界沖煮冠軍。二次研磨去掉銀皮提升乾淨度；自己調配礦物質比例的水，讓果酸與甜感更集中。',
      src: 'Sprudge、Barista Magazine、Timer.coffee' },
    { id: 'winton2021', year: 2021, comp: 'WBrC', who: 'Matt Winton', en: 'Matt Winton', country: '瑞士', title: '五段等量注水',
      bean: 'kenya', process: 'washed', roast: 'light', method: 'v60',
      cfg: { dose: 20, water: 300, temp: 93, grind: 700, schedule: P([[0, 60, { style: 'pulse' }], [40, 60, { style: 'pulse' }], [80, 60, { style: 'pulse' }], [120, 60, { style: 'pulse' }], [160, 60, { style: 'pulse' }]]) },
      steps: ['20 g 粉、300 g 水、93°C，V60', '五次各 60 g，每次等上一段快滴完再注', '先注中心再往外繞，注水積極', '不攪拌，約 3:30 完成'],
      idea: '把「不攪拌」當成原則，靠五次注水本身的擾動均勻萃取。自由組的豆子更在比賽史上首次混合了 Coffea eugenioides 與阿拉比卡兩個物種。',
      src: 'Barista Hustle 訪談、Honest Coffee Guide' },
    { id: 'sherry2022', grindKnown: true, year: 2022, comp: 'WBrC', who: '徐詩媛', en: 'Sherry Hsu', country: '臺灣', title: '雙研磨度＋冷熱雙溫',
      bean: 'geisha', process: 'carbonic', roast: 'light', method: 'v60',
      cfg: { dose: 14, water: 200, temp: 95, grind: 950, grindSplit: [{ g: 10.5, d: 1000 }, { g: 3.5, d: 800 }], schedule: P([[0, 50, { temp: 75, style: 'spiral' }], [30, 50, { temp: 95, style: 'spiral' }], [60, 50, { temp: 95, style: 'center' }], [90, 50, { temp: 95, style: 'center' }]]) },
      steps: ['14 g 粉：10.5 g 約 1000 µm（建構酸質）＋ 3.5 g 約 800 µm（增加甜感）', '粉水比 1:14，共 200 g，每 30 秒注 50 g', '第一段 75°C 繞圈，第二段 95°C 繞圈', '第三、四段 95°C 中心定點'],
      idea: '繼王策之後第二位臺灣世界沖煮冠軍。用哥倫比亞 Finca Mikava 的二氧化碳浸漬日曬藝伎，把研磨拆成粗、細兩種各司其職，再用低溫首注保護香氣。濾杯型號未公開，模擬以 V60 近似；本模型對「極粗研磨＋低溫首注」估得偏保守，模擬萃取率會低於實際。',
      src: '工商時報、天下雜誌、Melbourne WCC' },
    { id: 'medina2023', grindKnown: true, year: 2023, comp: 'WBrC', who: 'Carlos Medina', en: 'Carlos Medina', country: '智利', title: '五段等量＋低 TDS 水',
      bean: 'geisha', process: 'washed', roast: 'light', method: 'origami',
      cfg: { dose: 15.5, water: 250, temp: 91, grind: 840, waterProfile: 'soft', schedule: P([[0, 50], [30, 50], [60, 50], [90, 50], [120, 50]]) },
      steps: ['15.5 g 中粗研磨（約 840 µm）', 'Origami Air S 搭配錐形濾紙，91°C', '0:00、0:30、1:00、1:30、2:00 各注 50 g', '總時間約 2:40', '水 TDS 約 65 ppm，鈣鎂各半'],
      idea: '粗研磨、較低水溫、低礦物質水，全部指向「乾淨與清晰」。固定間隔等量注水讓流程容易重現。',
      src: 'Slow Pour Supply、Origami 官方專訪' },
    { id: 'wolfl2024', grindKnown: true, year: 2024, comp: 'WBrC', who: 'Martin Wölfl', en: 'Martin Wölfl', country: '奧地利', title: '快速平底濾杯',
      bean: 'geisha', process: 'natural', roast: 'light', method: 'orea',
      cfg: { dose: 17, water: 270, temp: 93, grind: 630, grinder: 'premium', schedule: P([[0, 60], [30, 60, { dur: 10 }], [40, 50, { dur: 40 }], [80, 100, { dur: 40 }]]) },
      steps: ['17 g 研磨 630 µm，270 g 水、93°C', 'OREA V4 Fast ＋ Sibarist FAST 濾紙', '60 g 悶蒸約 30 秒 → 0:40 前再加 60 g', '1:20 前加 50 g → 2:00 前加完最後 100 g'],
      idea: '用巴拿馬 Finca Maya 的藝伎（Lost Origin 處理）。快速濾杯讓他可以用較細研磨萃取出甜感，同時把總時間壓在兩分鐘出頭，保持乾淨。',
      src: 'European Coffee Trip、Wildkaffee 官網' },
    { id: 'peng2025', year: 2025, comp: 'WBrC', who: 'George Jinyang Peng', en: 'George Jinyang Peng', country: '中國', title: '溫度說故事',
      bean: 'geisha', process: 'washed', roast: 'light', method: 'origami',
      cfg: { dose: 15, water: 210, temp: 96, grind: 600, grinder: 'premium', waterProfile: 'soft', phys: { tau0: 13, bypass: 0.02 }, schedule: P([[0, 30, { temp: 96 }], [30, 90, { temp: 96 }], [70, 90, { temp: 80, style: 'melodrip' }]]) },
      steps: ['15 g 粉（FM 磨豆機 11 格），210 g 水，40 ppm 水', 'SOLO 濾杯（無旁流設計）＋ Sibarist FAST 濾紙', '0:00 注 30 g、96°C → 0:30 注 90 g、96°C', '1:10 用 Melodrip 分水網注 90 g、80°C', '總時間約 1:45'],
      idea: '從烘焙、沖煮到出杯都用溫度當主軸：高溫先把甜與重量萃出，最後一段降到 80°C、用分水網幾乎不擾動粉層，只補上乾淨的酸質與香氣。豆子來自巴拿馬 Mount Totumas 雲霧林。研磨微米數為推估，模擬以低旁流錐形濾杯近似 SOLO。',
      src: 'Sprudge、Slow Pour Supply、European Coffee Trip' },
    { id: 'hoffv60', year: 2007, comp: 'WBC', who: 'James Hoffmann', en: 'James Hoffmann', country: '英國', title: 'V60 終極技法（居家配方）',
      bean: 'huila', process: 'washed', roast: 'light', method: 'v60',
      cfg: { dose: 30, water: 500, temp: 96, grind: 650, schedule: P([[0, 60], [45, 240, { dur: 30 }], [75, 200, { dur: 30 }]]), events: [{ t: 12, type: 'swirl' }, { t: 108, type: 'stir', boost: 0.4 }, { t: 115, type: 'swirl' }] },
      steps: ['30 g 粉、500 g 水，水溫盡量高（淺焙用剛離火的水）', '60 g 悶蒸並搖晃濾杯，等 45 秒', '1:15 前注到 300 g，1:45 前注到 500 g', '用湯匙輕攪一圈再搖晃，讓粉床平整', '約 3:30 滴完'],
      idea: '2007 年世界咖啡師冠軍，後來以 YouTube 教學影響全球。這個技法重點在悶蒸時的搖晃與最後的平整粉床，追求可重複性。',
      src: 'James Hoffmann〈The Ultimate V60 Technique〉' },
    { id: 'hofffp', year: 2007, comp: 'WBC', who: 'James Hoffmann', en: 'James Hoffmann', country: '英國', title: '法壓壺長時間靜置法',
      bean: 'antigua', process: 'washed', roast: 'medium', method: 'frenchpress',
      cfg: { dose: 30, water: 500, temp: 98, grind: 1000, steep: 240, mode: 'hoffmann', wait: 300, stirs: [] },
      steps: ['30 g 中等偏粗研磨、500 g 剛沸騰的水', '靜置 4 分鐘，不攪拌', '4:00 用湯匙破開表面粉層，撈掉浮沫', '再等 5–8 分鐘讓細粉沉到底', '把濾網壓到液面就好，慢慢倒出，不要壓到底'],
      idea: '把法壓壺最大的缺點「混濁」交給時間處理：細粉沉澱後再倒出，得到乾淨度接近濾紙、又保有油脂的一杯。',
      src: 'James Hoffmann〈The Ultimate French Press Technique〉' },
    { id: 'hoffaero', year: 2007, comp: 'WBC', who: 'James Hoffmann', en: 'James Hoffmann', country: '英國', title: '愛樂壓正放法',
      bean: 'rwanda', process: 'washed', roast: 'light', method: 'aeropress',
      cfg: { dose: 11, water: 200, temp: 99, grind: 600, steep: 120, stirs: [], swirlAt: 120, press: 30, dilute: 0 },
      steps: ['11 g 細研磨、200 g 剛沸騰的水', '正放，插上活塞一點點形成真空，避免滴漏', '浸泡 2 分鐘', '拿起整組輕輕旋轉，再等 30 秒', '輕壓約 30 秒'],
      idea: '簡單、低粉量，強調「不用倒置也能做好」。長浸泡加輕壓，讓萃取穩定又不過度。',
      src: 'James Hoffmann〈The Ultimate AeroPress Technique〉' },
    { id: 'berg2016', year: 2016, comp: 'WBC', who: '吳則霖', en: 'Berg Wu', country: '臺灣', title: '藝伎濃縮',
      bean: 'geisha', process: 'washed', roast: 'light', method: 'espresso',
      cfg: { dose: 19, yield: 43, temp: 93, grind: 240, pressure: 9, preinf: 5, prep: 'screen', grinder: 'flat' },
      steps: ['19 g 粉 → 43 g 濃縮液（約 1:2.3）', '巴拿馬 Finca Deborah 藝伎', '報導中 TDS 約 9–9.5%', '水溫與時間未公開，模擬以 93°C 推估'],
      idea: '亞洲第一位世界咖啡師冠軍。用比傳統稍長的比例萃取淺焙藝伎，先是茉莉花香，接著柳橙、柑橘的高強度酸質，最後以蜂蜜收尾。',
      src: 'Perfect Daily Grind、Sprudge' },
    { id: 'jasin2024', year: 2024, comp: 'WBC', who: 'Mikael Jasin', en: 'Mikael Jasin', country: '印尼', title: '1:2.5 長比例濃縮',
      bean: 'geisha', process: 'washed', roast: 'light', method: 'espresso',
      cfg: { dose: 18, yield: 45, temp: 93, grind: 250, pressure: 9, preinf: 5, prep: 'screen', grinder: 'premium' },
      steps: ['比例 1:2.5（粉量推估 18 g → 45 g）', '巴拿馬 Finca Deborah 藝伎', '風味：茉莉、橙花、柳橙、蜂蜜，尾韻像金黃葡萄乾'],
      idea: '東南亞第一位世界咖啡師冠軍。淺焙藝伎用較長比例拉開酸質、降低濃度，讓花香更清楚。',
      src: 'Sprudge、Daily Coffee News' },
    { id: 'tay2023', year: 2023, comp: 'WAC', who: 'Tay Wipvasutt', en: 'Tay Wipvasutt', country: '泰國', title: '倒置法濃縮萃取',
      bean: 'kenya', process: 'washed', roast: 'light', method: 'aeropress',
      cfg: { dose: 18, water: 100, temp: 89, grind: 600, steep: 95, stirs: [30, 55], press: 30, dilute: 80, invert: true },
      steps: ['倒置，18 g（先 16 g，0:45 再加 2 g），ZP6 磨豆機 65 格', '100 g、89°C 的水，0:30 攪拌 5 秒', '0:45 補 2 g 粉，0:55 再攪拌 5 秒', '1:35 翻轉並下壓約 30 秒，得約 75 g', '先加常溫水到 115 g，再加熱水到 155 g'],
      idea: '先做出高濃度的萃取液，再用冷、熱兩段加水稀釋：冷水保留香氣，熱水把溫度拉回適飲。豆子是肯亞涅里 Karindundu 水洗 AB。研磨微米數為推估，中途補粉在模擬中以一開始就放 18 g 近似。',
      src: 'World AeroPress Championship 官方配方' },
    { id: 'sca', year: null, comp: '基準', who: 'SCA 金杯', en: 'SCA Golden Cup', country: '', title: '教科書標準',
      bean: 'huila', process: 'washed', roast: 'medium', method: 'kalita',
      cfg: { dose: 16.5, water: 300, temp: 93, grind: 700, schedule: P([[0, 50], [40, 125], [90, 125]]) },
      steps: ['每 1 公升水約 55 g 粉（約 1:18）', '水溫 92–96°C', '目標 EY 18–22%、TDS 1.15–1.35%'],
      idea: '美國精品咖啡協會的金杯標準，是所有沖煮控制圖的起點。',
      src: 'SCA Brewing Best Practices' }
  ];

  const HISTORY = {
    wbrc: [
      [2011, 'Keith O\'Sullivan', '愛爾蘭'], [2012, 'Matt Perger', '澳洲'], [2013, 'James McCarthy', '愛爾蘭'],
      [2014, 'Stefanos Domatiotis', '希臘'], [2015, 'Odd-Steinar Tøllefsen', '挪威'], [2016, '粕谷哲 Tetsu Kasuya', '日本'],
      [2017, '王策 Chad Wang', '臺灣'], [2018, '深堀絵美 Emi Fukahori', '瑞士'], [2019, '杜佳寧 Du Jianing', '中國'],
      [2021, 'Matt Winton', '瑞士'], [2022, '徐詩媛 Sherry Hsu', '臺灣'], [2023, 'Carlos Medina', '智利'],
      [2024, 'Martin Wölfl', '奧地利'], [2025, 'George Jinyang Peng', '中國']
    ],
    wbc: [
      [2000, 'Robert Thoresen', '挪威', '第一屆世界咖啡師大賽'], [2007, 'James Hoffmann', '英國', '後來成為最具影響力的咖啡 YouTuber'],
      [2014, '井崎英典 Hidenori Izaki', '日本', '亞洲第一位 WBC 冠軍'], [2015, 'Sasa Sestic', '澳洲', '把二氧化碳浸漬處理法帶進咖啡'],
      [2016, '吳則霖 Berg Wu', '臺灣', '臺灣第一位世界咖啡師冠軍'], [2017, 'Dale Harris', '英國', ''],
      [2018, 'Agnieszka Rojewska', '波蘭', '第一位女性 WBC 冠軍'], [2019, 'Jooyeon Jeon', '韓國', ''],
      [2021, 'Diego Campos', '哥倫比亞', '產地國咖啡師奪冠'], [2022, 'Anthony Douglas', '澳洲', ''],
      [2023, 'Boram Um', '英國', ''], [2024, 'Mikael Jasin', '印尼', '東南亞第一位 WBC 冠軍'], [2025, 'Jack Simpson', '澳洲', '連續三年進入前三名後奪冠']
    ]
  };

  const DATA = { BEANS, PROCESSES, ROAST_INFO, GRINDER_INFO, WATER_INFO, METHODS, TARGETS, RECIPES, HISTORY, STYLE_NAMES };
  if (typeof module !== 'undefined' && module.exports) module.exports = DATA;
  else root.COFFEE = DATA;
})(typeof window !== 'undefined' ? window : globalThis);
